apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: lab-gateway
  namespace: gateway-lab
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.gateway.local"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "secure.gateway.local"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: gateway-lab-tls
      allowedRoutes:
        namespaces:
          from: Same
