apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: basic-route
  namespace: gateway-lab
spec:
  parentRefs:
    - name: lab-gateway
      kind: Gateway
  hostnames:
    - basic.gateway.local
  rules:
    - backendRefs:
        - name: stable
          port: 8080
